name: Aequitas
version: '${project.version}'
main: top.cmarco.aequitas.Aequitas
api-version: '1.20'
authors: [CMarcoo]
description: Aequitas Anticheat for SpigotMC Servers
commands:
  aequitas:
    description: 'Main command of aequitas anti-cheat software.'
